### ISSUE TITLE
Configuration descriptor larger than control transfer max length

### ISSUE THREAD

**Issue by hdsjulian** [touchgadget/esp32-usb-host-demos#17]
With one MIDI Keybaord everything works. With the other i get: 
E (954) HUB: Configuration descriptor larger than control transfer max length
E (954) HUB: Stage failed: CHECK_SHORT_CONFIG_DESC
[  1292][I][usbhhelp.hpp:108] usbh_task(): [] No more devices

The Keyboard that works is an LPK25, the other registers as NC2-CONTROLLER. 
I somehow first assumed it might have to do with USB_HID_DESC_SIZE in show_desc.hpp, but that is not the case. Changing the value to 24 instead of 9 didn't do the trick. 
My knowledge of USB and everything is not enough. Any ideas what could help me? Is there a good way of debugging it?

**Comment by serifpersia** [comment]
> With one MIDI Keybaord everything works. With the other i get: E (954) HUB: Configuration descriptor larger than control transfer max length E (954) HUB: Stage failed: CHECK_SHORT_CONFIG_DESC [ 1292][I][usbhhelp.hpp:108] usbh_task(): [] No more devices
> 
> The Keyboard that works is an LPK25, the other registers as NC2-CONTROLLER. I somehow first assumed it might have to do with USB_HID_DESC_SIZE in show_desc.hpp, but that is not the case. Changing the value to 24 instead of 9 didn't do the trick. My knowledge of USB and everything is not enough. Any ideas what could help me? Is there a good way of debugging it?

I closed same issue with a solution #13. You can read more about it there as well as how I solved it in more details below.

Some MIDI devices have big config descriptor(default is 256) and for some midi devices this is not big enough. The fix is to custom compile esp32 arduino core sdk with new value for this parameter(I compiled mine with max 4096 bytes). You can find gdrive link in my esp32 [project](https://github.com/serifpersia/pianolux-esp32/blob/main/ESP32_PianoLux/ESP32_PianoLux.ino#L21) if you want to quickly fix this issue(s2/s3 2.0.14 arduino core esp32 sdks)

**Comment by civet** [comment]
@serifpersia Could you tell me how to recompile the SDK? I have tried many times but failed. Whether in a Linux environment or Docker, errors always occur. Which version is the usable one?

I am using PlatformIO, and it seems that the SDK is not the latest, so I am not sure if replacing the files will work.

**Comment by serifpersia** [comment]
> [@serifpersia](https://github.com/serifpersia) Could you tell me how to recompile the SDK? I have tried many times but failed. Whether in a Linux environment or Docker, errors always occur. Which version is the usable one?
> 
> I am using PlatformIO, and it seems that the SDK is not the latest, so I am not sure if replacing the files will work.

Sorry sadly I can't recall how its done but I think it was via menuconfig. I think I had to use linux to do the compilation You can find compiled sdks for s2/s3 on my pianolux-esp32 project I think its older v2 sdk(my first reply above). Yes I also had issues with errors back then you needed specific branch and so on.

**Comment by civet** [comment]
@serifpersia Thank you for your tips. Your project looks very interesting.

After several days of hard work, I finally managed to get it to compile on Ubuntu 22.04 with Python 3.10. 
`CONFIG_USB_HOST_CONTROL_TRANSFER_MAX_SIZE=4096` has already been added to sdkconfig.

Many errors occurred, I can only solve them calmly. 
I just realized that they no longer provide support for the old version branches. The main problem is that their script has issues. see: https://github.com/espressif/esp32-arduino-lib-builder/issues/292
Apart from this, I don't know why, I'm using branch `release/v2.x`  but in the end I had to use NIMBLE instead of Bluedroid to solve the compilation errors. see: https://github.com/espressif/arduino-esp32/issues/11822
